# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lda_rcpp <- function(d, w, z, weight, prior, alpha, beta, T, knowndiseases, burnin, ITER) {
    .Call('_sureLDA_lda_rcpp', PACKAGE = 'sureLDA', d, w, z, weight, prior, alpha, beta, T, knowndiseases, burnin, ITER)
}

lda_pred_rcpp <- function(weight, X, prior, phi, err = 0.1) {
    .Call('_sureLDA_lda_pred_rcpp', PACKAGE = 'sureLDA', weight, X, prior, phi, err)
}

